---
apiVersion: v1
kind: Service
metadata:
  name: orders-api                       # service name
spec:
  selector:
    app: orders-api     # "send traffic to pods with this label"
  ports:
    - port: {{ .Values.servicePort }}                      
      targetPort: {{ .Values.containerPort }}                    